import Link from "next/link";
import { Check, CircleSlash, Sparkles } from "lucide-react";
import { Topbar } from "@/components/shell/topbar";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { PulseScore } from "@/components/data/pulse-score";
import { alerts, customerById } from "@/lib/mock/data";
import { cn, relativeTime } from "@/lib/utils";
import type { AlertSeverity } from "@/lib/types";

const SEVERITY_LABEL: Record<AlertSeverity, string> = {
  critical: "Critical",
  warning: "Warning",
  info: "Info",
};

const SEVERITY_STRIPE: Record<AlertSeverity, string> = {
  critical: "bg-brick",
  warning: "bg-rust",
  info: "bg-slate",
};

const SEVERITY_BADGE: Record<AlertSeverity, "brick" | "rust" | "neutral"> = {
  critical: "brick",
  warning: "rust",
  info: "neutral",
};

export default function AlertsPage() {
  const open = alerts.filter((a) => a.status === "open");
  const acknowledged = alerts.filter((a) => a.status === "acknowledged");
  const resolved = alerts.filter((a) => a.status === "resolved");

  return (
    <>
      <Topbar
        kicker="Monitoring"
        title="Alerts feed"
        trailing={
          <div className="hidden md:flex items-center gap-1.5 mono text-[11px] text-ink-3">
            <span className="size-1.5 rounded-full bg-brick animate-pulse" />
            {open.length} open · {acknowledged.length} in progress
          </div>
        }
      />

      <div className="flex-1 px-6 lg:px-8 py-8 max-w-[1100px] w-full mx-auto rise space-y-10">
        {/* Lede */}
        <section className="space-y-2">
          <p className="kicker">Wire feed · last 7 days</p>
          <h2 className="display text-[36px] leading-tight text-ink max-w-3xl">
            <span className="display-num text-brick-deep">{open.length}</span> open
            alerts, sorted by severity.
          </h2>
          <p className="text-sm text-ink-2 max-w-xl">
            Each alert is generated by a churn-risk rule firing against new
            interactions. AI recommends the next action — you decide.
          </p>
        </section>

        {/* Filter row */}
        <div className="flex flex-wrap items-center gap-1.5 border-y border-rule py-3">
          <Chip active>
            All <span className="mono text-[10px] text-ink-3 ml-1">{alerts.length}</span>
          </Chip>
          <Chip>
            <span className="size-1.5 rounded-full bg-brick mr-1.5" />
            Critical <span className="mono text-[10px] ml-1">{alerts.filter((a) => a.severity === "critical").length}</span>
          </Chip>
          <Chip>
            <span className="size-1.5 rounded-full bg-rust mr-1.5" />
            Warning <span className="mono text-[10px] ml-1">{alerts.filter((a) => a.severity === "warning").length}</span>
          </Chip>
          <Chip>
            <span className="size-1.5 rounded-full bg-slate mr-1.5" />
            Info <span className="mono text-[10px] ml-1">{alerts.filter((a) => a.severity === "info").length}</span>
          </Chip>
          <span className="mx-2 h-4 w-px bg-rule" />
          <Chip>Sustained negative</Chip>
          <Chip>Repeated complaint</Chip>
          <Chip>Pulse drop</Chip>
          <Chip>Compliance</Chip>
        </div>

        {/* Open */}
        <Section title="Open" count={open.length} kicker="Needs attention">
          {open.map((a) => (
            <AlertCard key={a.id} alert={a} />
          ))}
        </Section>

        {acknowledged.length > 0 && (
          <Section title="In progress" count={acknowledged.length} kicker="Acknowledged">
            {acknowledged.map((a) => (
              <AlertCard key={a.id} alert={a} muted />
            ))}
          </Section>
        )}

        {resolved.length > 0 && (
          <Section title="Resolved" count={resolved.length} kicker="Closed">
            {resolved.map((a) => (
              <AlertCard key={a.id} alert={a} muted />
            ))}
          </Section>
        )}
      </div>
    </>
  );
}

function Section({
  title,
  count,
  kicker,
  children,
}: {
  title: string;
  count: number;
  kicker: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <div className="flex items-baseline gap-3 mb-4">
        <span className="kicker">{kicker}</span>
        <span className="h-px flex-1 bg-rule" />
        <span className="display text-xl text-ink">
          {title}
          <span className="mono text-sm text-ink-3 ml-2">{count}</span>
        </span>
      </div>
      <ul className="space-y-3">{children}</ul>
    </section>
  );
}

function AlertCard({
  alert,
  muted,
}: {
  alert: (typeof alerts)[number];
  muted?: boolean;
}) {
  const c = customerById(alert.customerId);
  return (
    <li
      className={cn(
        "relative bg-card border border-rule rounded-[5px] overflow-hidden flex",
        muted && "opacity-65",
      )}
    >
      {/* severity stripe */}
      <div className={cn("w-[3px] shrink-0", SEVERITY_STRIPE[alert.severity])} />

      <div className="flex-1 grid lg:grid-cols-[1fr_auto] gap-4">
        <div className="p-5">
          {/* meta */}
          <div className="flex items-center gap-2 mb-2">
            <Badge tone={SEVERITY_BADGE[alert.severity]}>
              {SEVERITY_LABEL[alert.severity]}
            </Badge>
            <span className="kicker">{alert.type}</span>
            <span className="ml-auto mono text-[10.5px] text-ink-3 whitespace-nowrap">
              {relativeTime(alert.createdAt)}
            </span>
          </div>

          {/* headline */}
          <Link
            href={`/dashboard/customers/${alert.customerId}`}
            className="display text-[22px] leading-tight text-ink hover:underline underline-offset-4 decoration-rule-strong"
          >
            {alert.customerName}.
          </Link>

          <p className="text-[14px] text-ink-2 leading-relaxed mt-2 mb-4 max-w-prose">
            {alert.message}
          </p>

          {/* AI recommendation block */}
          <div className="bg-paper-2 border border-rule rounded-[4px] p-3.5 max-w-prose">
            <div className="flex items-center gap-1.5 mb-1.5">
              <Sparkles className="size-3 text-rust" strokeWidth={1.75} />
              <span className="kicker !text-[9px]">AI · recommended next action</span>
            </div>
            <p className="text-[13px] text-ink leading-relaxed">{alert.recommendation}</p>
          </div>

          {/* footer actions */}
          <div className="mt-4 flex flex-wrap items-center gap-2">
            <Button variant="primary" size="sm">
              <Check className="size-3" />
              Acknowledge
            </Button>
            <Button variant="secondary" size="sm">
              Draft outreach
            </Button>
            <Button variant="ghost" size="sm">
              <CircleSlash className="size-3" />
              Dismiss
            </Button>
            <span className="ml-auto mono text-[10.5px] text-ink-3">
              alert id · <span className="text-ink-2">{alert.id}</span>
            </span>
          </div>
        </div>

        {/* right rail — pulse at moment of alert */}
        {c && (
          <aside className="hidden lg:flex flex-col items-end gap-2 border-l border-rule px-5 py-5 bg-paper-2/40 min-w-[160px]">
            <div className="kicker !text-[9px]">Pulse · now</div>
            <PulseScore value={c.pulse} size="md" />
            <div className="kicker !text-[9px] mt-2">at alert time</div>
            <div className="display-num text-2xl text-ink-3 tabular">{alert.pulseAtAlert}</div>
            <div className="mt-auto pt-2 border-t border-rule w-full">
              <div className="kicker !text-[9px] mb-1">Segment</div>
              <div className="text-[11.5px] text-ink-2">{c.segment}</div>
              <div className="text-[11px] text-ink-3 mt-0.5">{c.industry}</div>
            </div>
          </aside>
        )}
      </div>
    </li>
  );
}

function Chip({ children, active }: { children: React.ReactNode; active?: boolean }) {
  return (
    <button
      className={cn(
        "inline-flex items-center px-2.5 h-7 text-xs rounded-[3px] border transition-colors",
        active
          ? "bg-ink text-paper border-ink"
          : "bg-card text-ink-2 border-rule hover:border-ink-3 hover:text-ink",
      )}
    >
      {children}
    </button>
  );
}
